name: Draft a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number (e.g. 1.2.3) OR one of: patch|minor|major|prepatch|preminor|premajor|prerelease'
        required: true
        default: 'patch'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Update version
        id: updated_version
        shell: bash
        run: |
          uvx --from rust-just just bump ${{ github.event.inputs.version }}
      
      - name: Create a draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.updated_version.outputs.version }}
          release_name: Release ${{ steps.updated_version.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true