name: Release

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Install dependencies
        run: uv sync --dev
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish # you need to do this https://docs.pypi.org/trusted-publishers/adding-a-publisher/
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
